<a href="https://colab.research.google.com/github/SaurabhIndi/UM-Projects/blob/main/fraud_2_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Setup Google Colab

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

## 2. Load Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_pickle('/content/drive/MyDrive/datasetforfraud/2018-09-18.pkl')  # Replace with the path to your file

## 3. Explore Dataset

In [ ]:
print(data.head())
print(data.info())
print(data.describe())

         TRANSACTION_ID         TX_DATETIME CUSTOMER_ID TERMINAL_ID  \
1629448         1629448 2018-09-18 00:00:08        3368        4427   
1629449         1629449 2018-09-18 00:00:46        1439         827   
1629450         1629450 2018-09-18 00:01:05        4211        8810   
1629451         1629451 2018-09-18 00:02:14        3795        8113   
1629452         1629452 2018-09-18 00:02:56         763        8310   

         TX_AMOUNT TX_TIME_SECONDS TX_TIME_DAYS  TX_FRAUD  TX_FRAUD_SCENARIO  
1629448      31.72        14688008          170         0                  0  
1629449      12.35        14688046          170         0                  0  
1629450       3.37        14688065          170         0                  0  
1629451      52.26        14688134          170         0                  0  
1629452      77.75        14688176          170         0                  0  
<class 'pandas.core.frame.DataFrame'>
Index: 9635 entries, 1629448 to 1639082
Data columns (total 9

## 4. Data Preprocessing

In [ ]:
data.fillna(method='ffill', inplace=True)  # Forward fill missing values

<ipython-input-6-76f0634cb0dd>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)  # Forward fill missing values
<ipython-input-6-76f0634cb0dd>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.fillna(method='ffill', inplace=True)  # Forward fill missing values


In [ ]:
# Assuming 'TERMINAL_ID' is categorical
data['TERMINAL_ID'] = data['TERMINAL_ID'].astype('category').cat.codes

In [ ]:
scaler = StandardScaler()
data[['TX_AMOUNT']] = scaler.fit_transform(data[['TX_AMOUNT']])

## 5. Feature Engineering

In [ ]:
data['TX_HOUR'] = data['TX_DATETIME'].dt.hour
data['TX_DAYOFWEEK'] = data['TX_DATETIME'].dt.dayofweek

## 6. Split Dataset

In [ ]:
X = data.drop('TX_FRAUD', axis=1)
y = data['TX_FRAUD']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 7. Model Training and Evaluating (Attempt-1)

In [ ]:
# Drop 'TX_DATETIME' column before splitting the data
X = data.drop(['TX_FRAUD', 'TX_DATETIME'], axis=1)
y = data['TX_FRAUD']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()  # Or RandomForestClassifier()
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 0.9922158796056045
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[1912    0]
 [  15    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


#### UNEXPECTED EVALUATION

## 8. Oversampling: Duplicate minority class (fraudulent) transactions to balance the dataset. Libraries like imbalanced-learn can help with this.

In [ ]:
from imblearn.over_sampling import SMOTE

# ... (rest of your code)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Oversample the minority class
smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

# Train your model
model.fit(X_train, y_train)

# Make predictions and evaluate
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 0.9029579657498703
Precision: 0.07
Recall: 0.9333333333333333
F1-score: 0.13023255813953488
Confusion Matrix:
 [[1726  186]
 [   1   14]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#### Improved Evaluation Metrics

# Attempt to improve the model

####

1.  Scaling Data
2.   Using different model



In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model.fit(X_train_scaled, y_train)  # Train with scaled data

LogisticRegression()

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
from imblearn.over_sampling import SMOTE

# ... (rest of your code)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Oversample the minority class
smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

# Train your model
model.fit(X_train, y_train)

# Make predictions and evaluate
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
Confusion Matrix:
 [[1912    0]
 [   0   15]]
